### ISSUE TITLE
pinard top-level init references non-existant pipeline module

### ISSUE THREAD

**Issue by untzag** [GBeurier/pinard#14]
**Describe the bug**

Pinard `__init__` references `pipeline` in `__all__`, the pipeline module does not exist.

**To Reproduce**

```python
>>> from pinard import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pinard' has no attribute 'pipeline'
```

**Expected behavior**

No attribute error when importing all.

**Desktop (please complete the following information):**

Debian, Intel, NVIDIA

**Comment by GBeurier** [comment]
There was a problem with the naming.
commit dd7acabdc2725e0081fa828d231c9db93663db4b fix it.

**Comment by untzag** [comment]
Thanks @GBeurier
