### ISSUE TITLE
tests fail on my machine

### ISSUE THREAD

**Issue by untzag** [GBeurier/pinard#16]
**Describe the bug**

Two out of your 40 tests fail on my machine. I would appreciate any insight you have regarding these failures.

**To Reproduce**

Clone pinard main.

`$ python -m pip install -e .`

`$ pytest`

Two of the selection tests fail. See log file:

[pytest.log](https://github.com/GBeurier/pinard/files/12315458/pytest.log)

**Expected behavior**

Pytest passes on my machine.

**Desktop (please complete the following information):**

Debian, Intel, Nvidia, Python 3.11.4

**Comment by GBeurier** [comment]
Test was failing because of a poor management of the random seed initialization.
Fixed in cd485db3f70067364965f351e0861655edf1440d
