### ISSUE TITLE
why are the requirements different between requirements.txt and setup.py?

### ISSUE THREAD

**Issue by untzag** [GBeurier/pinard#17]
Why are the requirements different between requirements.txt and setup.py? Do you have extra requirements that are optional, or are some missing from setup.py?

Most people expect to be able to fully run the software after cloning and running `python -m pip install .`

It looks like such a person would be missing e.g. `kennard-stone`.

**Comment by GBeurier** [comment]
It was an error.
Fixed in cd485db3f70067364965f351e0861655edf1440d

**Comment by untzag** [comment]
Thanks @GBeurier
