### ISSUE TITLE
ModuleNotFoundError: Cannot use SPlit sampling without tweening package.

### ISSUE THREAD

**Issue by pikakolendo02** [GBeurier/pinard#20]
When I want to use SPlit method, it says: 
`ModuleNotFoundError: Cannot use SPlit sampling without tweening package. See https://github.com/GBeurier/pinard`
What is the `tweening` package? There is no package names `tweening` in PyPI. I have installed `pytweening` but no help.

**Comment by GBeurier** [comment]
The reference was loaded locally and wrongly spelled.
Fixed in cd485db3f70067364965f351e0861655edf1440d
