### ISSUE TITLE
ByGroup argument to splitting

### ISSUE THREAD

**Issue by dcornet** [GBeurier/pinard#7]
If we are willing to include splitting methods in the pipeline, they should be associated with a byGroup argument allowing the user to specify a groupingID associated to each sample. This allow to use the data strcucture (e.g. by genotype, by species, by site, by year) during the splitting and allow more robustness to prediction based on new grouping element. An option could link the byGroup argument in the splitting method to the sklearn.model_selection.GroupKFold method.

**Comment by GBeurier** [comment]
It will be merged from DECON project in the next version.
